language: ruby
cache: bundler
rvm:
  - 2.0.0
before_script:
  - psql -c 'create database oereo_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
  - RAILS_ENV=test bundle exec rspec
  - RAILS_ENV=test bundle exec rake spec:javascript
